package utils

const (
	TerraformResourceProfileID           = "profile_id"
	TerraformResourceConfigRepo          = "config_repos"
	TerraformResourcePluginConfiguration = "plugin_configurations"
	TerraformResourceConfiguration       = "configuration"
	TerraformResourceClusterProfileID    = "cluster_profile_id"
	TerraformPluginID                    = "plugin_id"
	TerraformProperties                  = "properties"
	TerraformResourceKey                 = "key"
	TerraformResourceValue               = "value"
	TerraformResourceRules               = "rules"
	TerraformResourceMaterial            = "material"
	TerraformResourceENCValue            = "encrypted_value"
	TerraformResourceIsSecure            = "is_secure"
	TerraformResourceEtag                = "etag"
	TerraformResourceAttr                = "attributes"
	TerraformResourceType                = "type"
	TerraformResourceFgPrint             = "fingerprint"
	TerraformResourceURL                 = "url"
	TerraformResourceUserName            = "username"
	TerraformResourcePassword            = "password"
	TerraformResourceEncryptPassword     = "encrypted_password"
	TerraformResourceBranch              = "branch"
	TerraformResourceAutoUpdate          = "auto_update"
	TerraformResourceCheck               = "check_externals"
	TerraformResourceUseTickets          = "use_tickets"
	TerraformResourceView                = "view"
	TerraformResourcePort                = "port"
	TerraformResourceProjectPath         = "project_path"
	TerraformResourceDomain              = "domain"
	TerraformResourceRef                 = "ref"
	TerraformResourceName                = "name"
	TerraformResourceStage               = "stage"
	TerraformResourcePipeline            = "pipeline"
	TerraformResourceIgnoreForScheduling = "ignore_for_scheduling"
	TerraformResourceDestination         = "destination"
	TerraformResourceInvertFilter        = "invert_filter"
	TerraformResourceAllowKnownUser      = "allow_only_known_users_to_login"
	TerraformResourceIgnore              = "ignore"
	TerraformEncryptedValue              = "encrypted_value"
	TerraformValue                       = "value"
)
