version: "2"
run:
  concurrency: 10
  issues-exit-code: 1
  tests: true
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dupl
    - err113
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - gochecknoglobals
    - goconst
    - interfacebloat
    - ireturn
    - nolintlint
    - paralleltest
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    dupl:
      threshold: 450
    funlen:
      lines: 190
      statements: 60
    gocognit:
      min-complexity: 50
    lll:
      line-length: 165
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - mnd
        path: _test\.go
      - linters:
          - gocritic
        text: 'unnecessaryDefer:'
    paths:
      - Makefile
      - README.md
      - Dockerfile
      - scripts/
      - vendor/
      - docs/
      - third_party$
      - builtin$
      - examples$
severity:
  default: error
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - Makefile
      - README.md
      - Dockerfile
      - scripts/
      - vendor/
      - docs/
      - third_party$
      - builtin$
      - examples$
