---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "gocd_agent Resource - terraform-provider-gocd"
subcategory: ""
description: |-
  
---

# gocd_agent (Resource)
Update configuration of a specified agent by interacting with GoCD [api](https://api.gocd.org/current/#update-an-agent).

## Example Usage
```terraform
resource "gocd_agent" "sample_agent" {
    uuid = "bbfe3a75-7fd8-48db-af32-0a91b9efd0ab"
    agent_config_state = "ENABLED"
    environments = ["sample_environment_3"]
    resources = ["linux"]
    hostname = "sample.agent001.com"
}
```
**NOTE:** Since this resource updates the agent config, `terraform destroy` of this would just remove its reference from state and does not delete the agent itself.

<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `uuid` (String) The identifier of this agent.

### Optional

- `agent_config_state` (String) Whether an agent is enabled or not. Can be one of `Enabled`, `Disabled`.
- `environments` (List of String) The set of environments that this agent belongs to.
- `hostname` (String) The hostname of the agent.
- `ip_address` (String) The IP address of the agent.
- `operating_system` (String) The operating system as reported by the agent.
- `resources` (List of String) The set of resources that this agent is tagged with (if agent is not an elastic agent).

### Read-Only

- `id` (String) The ID of this resource.


