---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "gocd_artifact_store Resource - terraform-provider-gocd"
subcategory: ""
description: |-
  
---

# gocd_artifact_store (Resource)
Creates artifact store in GoCD with all below passed parameters by interacting with GoCD artifact store [api](https://api.gocd.org/current/#create-an-artifact-store).

## Example Usage
```terraform
resource "gocd_artifact_store" "docker" {
    store_id  = "docker"
    plugin_id = "cd.go.artifact.s3"
    properties {
        key   = "S3Bucket"
        value = "sample"
    }
    properties {
        key   = "Region"
        value = "ap-south-1"
    }
}
```

## Importing the existing GoCD artifact store to Terraform State
```terraform
resource "gocd_artifact_store" "docker" {
    store_id  = "docker"
}
```

```shell
# Once the above code is added, the resource can be imported by running the below command.
terraform import gocd_artifact_store.docker docker
```

<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `plugin_id` (String) The plugin identifier of the artifact plugin.
- `properties` (Block Set, Min: 1) The list of configuration properties that represent the configuration of the profile. (see [below for nested schema](#nestedblock--properties))
- `store_id` (String) The identifier of the artifact store.

### Read-Only

- `etag` (String) etag used to track the plugin settings
- `id` (String) The ID of this resource.

<a id="nestedblock--properties"></a>
### Nested Schema for `properties`

Required:

- `key` (String) the name of the property key.

Optional:

- `encrypted_value` (String) The encrypted value of the property
- `is_secure` (Boolean) Specify whether the given property is secure or not. If true and encrypted_value is not specified, GoCD will store the value in encrypted format.
- `value` (String) The value of the property


