---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "gocd_backup_config Resource - terraform-provider-gocd"
subcategory: ""
description: |-
  
---

# gocd_backup_config (Resource)
Creates a backup configuration in GoCD server with all below passed parameters by interacting with GoCD [api](https://api.gocd.org/current/#backup-config).

## Example Usage
```terraform
resource "gocd_backup_config" "nightly_backup" {
    schedule           = "0 0 2 * * ?"
    post_backup_script = "path/to/postbackup_script.sh"
    email_on_failure   = false
    email_on_success   = false
}
```


<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `schedule` (String) The backup schedule. See the quartz documentation for syntax and examples.

### Optional

- `email_on_failure` (Boolean) If set to true, an email will be sent when backup fails.
- `email_on_success` (Boolean) If set to true, an email will be sent when backup completes successfully.
- `post_backup_script` (String) The script that will be executed once the backup finishes. See the gocd documentation for details.

### Read-Only

- `id` (String) The ID of this resource.


