---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "gocd_elastic_agent_profile Resource - terraform-provider-gocd"
subcategory: ""
description: |-
  
---

# gocd_elastic_agent_profile (Resource)
Creates an elastic agent profiles in GoCD with all below passed parameters by interacting with elastic agent profiles [api](https://api.gocd.org/current/#elastic-agent-profiles).

## Example Usage
```terraform
resource "gocd_elastic_agent_profile" "sample_kubernetes" {
    profile_id         = "sample_kubernetes"
    cluster_profile_id = gocd_cluster_profile.kube_cluster_profile.profile_id
    properties {
        key   = "Image"
        value = "basnik/thanosbench:with-thanos"
    }
}
```

## Importing the existing cluster profile to Terraform State
```terraform
resource "gocd_elastic_agent_profile" "some_cluster_profile" {
    profile_id = "kube_cluster_profile"
}
```

```shell
# Once the above code is added, the resource can be imported by running the below command.
terraform import gocd_elastic_agent_profile.some_cluster_profile kube_cluster_profile
```

<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `cluster_profile_id` (String) the plugin identifier of the cluster profile.
- `profile_id` (String) the identifier of the elastic agent profile.
- `properties` (Block Set, Min: 1) the list of configuration properties that represent the configuration of this profile. (see [below for nested schema](#nestedblock--properties))

### Read-Only

- `etag` (String) etag used to track the elastic agent profile configurations
- `id` (String) The ID of this resource.

<a id="nestedblock--properties"></a>
### Nested Schema for `properties`

Required:

- `key` (String) the name of the property key.

Optional:

- `encrypted_value` (String) The encrypted value of the property
- `is_secure` (Boolean) Specify whether the given property is secure or not. If true and encrypted_value is not specified, GoCD will store the value in encrypted format.
- `value` (String) The value of the property


