---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "gocd_pipeline Resource - terraform-provider-gocd"
subcategory: ""
description: |-
  
---

# gocd_pipeline (Resource)
Creates a pipeline GoCD with all below passed parameters by interacting with create pipeline config [api](https://api.gocd.org/current/#create-a-pipeline).

## Example Usage
```terraform
resource "gocd_pipeline" "helm_drift" {
    name              = "helm-drift"
    pause_on_creation = true
    pause_reason      = "better to pause pipeline on creation"
    group             = "sample-group"
    config            = <<EOF
        environment_variables:
          - name: HELM_PLUGIN
            secure: false
            value: "false"
        lock_behavior: none
        materials:
        - attributes:
            auto_update: true
            branch: master
            destination: null
            filter: null
            invert_filter: false
            name: null
            shallow_clone: false
            submodule_folder: null
            url: "https://github.com/nikhilsbhat/helm-drift.git"
        type: git
        name: helm-drift
        parameters: []
        stages:
            - approval:
                allow_only_on_success: false
                authorization:
                    roles: []
                    users: []
                type: success
             clean_working_directory: false
             environment_variables: []
             fetch_materials: true
             jobs:
                - artifacts: []
                  environment_variables: []
                  name: lint
                  resources: []
                  run_instance_count: null
                  tabs: []
                  tasks:
                    - attributes:
                        arguments:
                        - lint
                        command: echo
                        run_if: []
                    type: exec
                  timeout: null
                  name: lint
                  never_cleanup_artifacts: false
        timer: null
        tracking_tool: null
EOF
}
```


<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `config` (String) The config of the selected pipeline (it can take in yaml/json data based on the attribute set).
- `group` (String) Name of the pipeline group that this pipeline should be part of.
- `name` (String) The name of the pipeline to be created (this should be the same that would be passed under `config`).

### Optional

- `etag` (String) Etag used to track the pipeline config
- `pause_on_creation` (Boolean) Enabling this would have the pipeline paused on creation
- `pause_reason` (String) Reason for pausing the pipeline on start

### Read-Only

- `id` (String) The ID of this resource.


