---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "gocd_agent Data Source - terraform-provider-gocd"
subcategory: ""
description: |-
  
---

# gocd_agent (Data Source)
Fetch the details of the GoCD Agent by interacting with GET agent [api](https://api.gocd.org/current/#get-one-agent).

## Example Usage
```terraform
data "gocd_agent" "sample_agent" {
    uuid = "4c92e7e3-8abd-4b02-a7eb-c46b2c7ac674"
}
```


<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `uuid` (String) The identifier of this agent.

### Optional

- `agent_config_state` (String) Whether an agent is enabled or not. Can be one of `Pending`, `Enabled`, `Disabled`.
- `agent_state` (String) The state an agent is in. Can be one of Idle, `Building`, `LostContact`, `Missing`, `Building`, `Unknown`.
- `agent_version` (String) The version of the agent.
- `build_details` (Map of String) The build details provides information like pipeline, stage and job if the build_state of the agent is `Building`
- `build_state` (String) If the agent is running a build, the state of the build on the agent. Can be one of Idle, `Building`, `Cancelled`, `Unknown`.
- `elastic_agent_id` (String) The elastic agent identifier of this agent. This attribute is only available if the agent is an elastic agent.
- `elastic_plugin_id` (String) The identifier of the elastic agent plugin that manages this agent instance. This attribute is only available if the agent is an elastic agent.
- `environments` (List of String) The set of environments that this agent belongs to.
- `free_space` (Number) The amount of free space in bytes.
- `hostname` (String) The hostname of the agent.
- `ip_address` (String) The IP address of the agent.
- `operating_system` (String) The operating system as reported by the agent.
- `resources` (List of String) The set of resources that this agent is tagged with (if agent is not an elastic agent).
- `sandbox` (String) The path where the agent will perform its builds.

### Read-Only

- `id` (String) The ID of this resource.


