---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "gocd_artifact_store Data Source - terraform-provider-gocd"
subcategory: ""
description: |-
  
---

# gocd_artifact_store (Data Source)
Fetch the details of the specified artifact store by interacting with GET artifact store [api](https://api.gocd.org/current/#get-an-artifact-store).

## Example Usage
```terraform
data "gocd_artifact_store" "docker" {
    store_id = gocd_artifact_store.docker.id
}
```


<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `store_id` (String) The identifier of the artifact store.

### Optional

- `etag` (String) Etag used to track an artifact store
- `plugin_id` (String) The plugin identifier of the artifact plugin.
- `properties` (Block List) The list of configuration properties that represent the configuration of this artifact store. (see [below for nested schema](#nestedblock--properties))

### Read-Only

- `id` (String) The ID of this resource.

<a id="nestedblock--properties"></a>
### Nested Schema for `properties`

Required:

- `key` (String) the name of the property key.

Optional:

- `encrypted_value` (String) The encrypted value of the property
- `is_secure` (Boolean) Specify whether the given property is secure or not. If true and encrypted_value is not specified, GoCD will store the value in encrypted format.
- `value` (String) The value of the property


