---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "gocd_elastic_agent_profile Data Source - terraform-provider-gocd"
subcategory: ""
description: |-
  
---

# gocd_elastic_agent_profile (Data Source)
Fetch the details of the specified elastic profile by interacting with GET elastic profile [api](https://api.gocd.org/current/#get-an-elastic-agent-profile).

## Example Usage
```terraform
data "gocd_elastic_agent_profile" "sample_ec2" {
    profile_id = gocd_elastic_agent_profile.sample_ec2.id
}
```


<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `profile_id` (String) The identifier of the elastic agent profile.

### Optional

- `cluster_profile_id` (String) The identifier of the cluster profile to which current elastic agent profile belongs.
- `etag` (String) Etag used to track the elastic agent profile.
- `properties` (Block List) The list of configuration properties that represent the configuration of this profile. (see [below for nested schema](#nestedblock--properties))

### Read-Only

- `id` (String) The ID of this resource.

<a id="nestedblock--properties"></a>
### Nested Schema for `properties`

Required:

- `key` (String) the name of the property key.

Optional:

- `encrypted_value` (String) The encrypted value of the property
- `is_secure` (Boolean) Specify whether the given property is secure or not. If true and encrypted_value is not specified, GoCD will store the value in encrypted format.
- `value` (String) The value of the property


