---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "gocd_environment Data Source - terraform-provider-gocd"
subcategory: ""
description: |-
  
---

# gocd_environment (Data Source)
Fetch the details of the specified environment by interacting with GET environment [api](https://api.gocd.org/current/#get-environment-config).

## Example Usage
```terraform
data "gocd_environment" "sample_environment" {
    name = gocd_environment.sample_environment.id
}
```


<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `name` (String) The name of environment.

### Optional

- `environment_variables` (Block List) The list of environment variables that will be passed to all tasks (commands) that are part of this environment. (see [below for nested schema](#nestedblock--environment_variables))
- `etag` (String) Etag used to track the environment configuration
- `pipelines` (List of String) List of pipeline names that should be added to this environment.

### Read-Only

- `id` (String) The ID of this resource.

<a id="nestedblock--environment_variables"></a>
### Nested Schema for `environment_variables`

Optional:

- `encrypted_value` (String) The encrypted value of the environment variable. You MUST specify one of value or encrypted_value.
- `name` (String) The name of the environment variable.
- `secure` (Boolean) Whether environment variable is secure or not. When set to true, encrypts the value if one is specified. The default value is false.
- `value` (String) The value of the environment variable. You MUST specify one of value or encrypted_value.


