---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "gocd_pipeline Data Source - terraform-provider-gocd"
subcategory: ""
description: |-
  
---

# gocd_pipeline (Data Source)
Fetches the config of specified pipeline present in GoCD by interacting with GET pipeline config [api](https://api.gocd.org/current/#get-pipeline-config).

## Example Usage
```terraform
data "gocd_pipeline" "helm_images" {
    name = "helm-images"
    yaml = true
}
```


<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `name` (String) The name of the pipeline to be retrieved.

### Optional

- `config` (String) The config of the selected pipeline (it would be in yaml/json based on the attribute set).
- `etag` (String) Etag used to track the pipeline config
- `yaml` (Boolean) When set, yaml equivalent config would be set under `config`.

### Read-Only

- `id` (String) The ID of this resource.


