---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "gocd_pipeline_group Data Source - terraform-provider-gocd"
subcategory: ""
description: |-
  
---

# gocd_pipeline_group (Data Source)
Fetches the specified pipeline group config present in GoCD by interacting with GET pipeline config [api](https://api.gocd.org/current/#get-a-pipeline-group).

## Example Usage
```terraform
data "gocd_pipeline_group" "sample_group" {
  group_id = "sample-group"
}
```


<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `group_id` (String) Name of the pipeline group to be retrieved.

### Optional

- `authorization` (Block Set) The authorization configuration for the pipeline group. (see [below for nested schema](#nestedblock--authorization))
- `etag` (String) Etag used to track the pipeline group.
- `pipelines` (List of String) List of pipelines those are part of this pipeline group.

### Read-Only

- `id` (String) The ID of this resource.

<a id="nestedblock--authorization"></a>
### Nested Schema for `authorization`

Optional:

- `admins` (Block Set) The list of users and roles with view permission for this pipeline group (see [below for nested schema](#nestedblock--authorization--admins))
- `operate` (Block Set) The list of users and roles with view permission for this pipeline group (see [below for nested schema](#nestedblock--authorization--operate))
- `view` (Block Set) The list of users and roles with view permission for this pipeline group (see [below for nested schema](#nestedblock--authorization--view))

<a id="nestedblock--authorization--admins"></a>
### Nested Schema for `authorization.admins`

Optional:

- `roles` (List of String) List of roles present in GoCD.
- `users` (List of String) List of users present in GoCD.


<a id="nestedblock--authorization--operate"></a>
### Nested Schema for `authorization.operate`

Optional:

- `roles` (List of String) List of roles present in GoCD.
- `users` (List of String) List of users present in GoCD.


<a id="nestedblock--authorization--view"></a>
### Nested Schema for `authorization.view`

Optional:

- `roles` (List of String) List of roles present in GoCD.
- `users` (List of String) List of users present in GoCD.


