// ----------------------------------------------------------------------------
//
//	***     TERRAGEN GENERATED CODE    ***    TERRAGEN GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//	This file was auto generated by Terragen.
//	This autogenerated code has to be enhanced further to make it fully working terraform-provider.
//
//	Get more information on how terragen works.
//	https://github.com/nikhilsbhat/terragen
//
// ----------------------------------------------------------------------------
//
//nolint:gocritic
package provider

import (
	"context"
	"log"

	"github.com/google/go-cmp/cmp"
	"github.com/nikhilsbhat/gocd-sdk-go"
	"github.com/nikhilsbhat/terraform-provider-gocd/pkg/utils"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func resourceClusterProfile() *schema.Resource {
	return &schema.Resource{
		CreateContext: resourceClusterProfileCreate,
		ReadContext:   resourceClusterProfileRead,
		DeleteContext: resourceClusterProfileDelete,
		UpdateContext: resourceClusterProfileUpdate,
		Schema: map[string]*schema.Schema{
			"profile_id": {
				Type:        schema.TypeString,
				Required:    true,
				Computed:    false,
				ForceNew:    true,
				Description: "the identifier of the cluster profile.",
			},
			"plugin_id": {
				Type:        schema.TypeString,
				Required:    true,
				Computed:    false,
				ForceNew:    true,
				Description: "the plugin identifier of the cluster profile.",
			},
			"properties": propertiesSchemaResource(),
			"etag": {
				Type:        schema.TypeString,
				Required:    false,
				Computed:    true,
				ForceNew:    false,
				Description: "etag used to track the plugin settings",
			},
		},
	}
}

func resourceClusterProfileCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	defaultConfig := meta.(gocd.GoCd)

	if !d.IsNewResource() {
		return nil
	}

	id := d.Id()

	if len(id) == 0 {
		newID, err := utils.GetRandomID()
		if err != nil {
			d.SetId("")

			return diag.Errorf("errored while fetching randomID %v", err)
		}
		id = newID
	}

	cfg := gocd.CommonConfig{
		ID:         utils.String(d.Get(utils.TerraformResourceProfileID)),
		PluginID:   utils.String(d.Get(utils.TerraformPluginID)),
		Properties: getPluginConfiguration(d.Get(utils.TerraformProperties)),
	}

	_, err := defaultConfig.CreateClusterProfile(cfg)
	if err != nil {
		return diag.Errorf("creating cluster profile %s setting for plugin %s errored with %v", cfg.ID, cfg.PluginID, err)
	}

	d.SetId(id)

	return resourceClusterProfileRead(ctx, d, meta)
}

func resourceClusterProfileRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	defaultConfig := meta.(gocd.GoCd)

	profileID := utils.String(d.Get(utils.TerraformResourceProfileID))
	response, err := defaultConfig.GetClusterProfile(profileID)
	if err != nil {
		return diag.Errorf("getting cluster profile configuration %s errored with: %v", profileID, err)
	}

	if err = d.Set(utils.TerraformResourceEtag, response.ETAG); err != nil {
		return diag.Errorf("setting etag errored with %v", err)
	}

	return nil
}

func resourceClusterProfileUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	defaultConfig := meta.(gocd.GoCd)

	if d.HasChange(utils.TerraformProperties) {
		oldCfg, newCfg := d.GetChange(utils.TerraformProperties)
		if !cmp.Equal(oldCfg, newCfg) {
			cfg := gocd.CommonConfig{
				ID:         utils.String(d.Get(utils.TerraformResourceProfileID)),
				PluginID:   utils.String(d.Get(utils.TerraformPluginID)),
				Properties: getPluginConfiguration(newCfg),
				ETAG:       utils.String(d.Get(utils.TerraformResourceEtag)),
			}

			_, err := defaultConfig.UpdateClusterProfile(cfg)
			if err != nil {
				return diag.Errorf("updating cluster profile %s errored with: %v", cfg.ID, err)
			}

			return resourceClusterProfileRead(ctx, d, meta)
		}
	}

	log.Printf("nothing to update so skipping")

	return nil
}

func resourceClusterProfileDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	defaultConfig := meta.(gocd.GoCd)

	id := d.Id()
	if len(d.Id()) == 0 {
		return diag.Errorf("resource with the ID '%s' not found", id)
	}

	profileID := utils.String(d.Get(utils.TerraformResourceProfileID))

	err := defaultConfig.DeleteClusterProfile(profileID)
	if err != nil {
		return diag.Errorf("deleting cluster profile %s errored with: %v", profileID, err)
	}

	d.SetId("")

	return nil
}
