// ----------------------------------------------------------------------------
//
//	***     TERRAGEN GENERATED CODE    ***    TERRAGEN GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//	This file was auto generated by Terragen.
//	This autogenerated code has to be enhanced further to make it fully working terraform-provider.
//
//	Get more information on how terragen works.
//	https://github.com/nikhilsbhat/terragen
//
// ----------------------------------------------------------------------------
//
//nolint:gocritic
package provider

import (
	"context"
	"log"

	"github.com/google/go-cmp/cmp"
	"github.com/nikhilsbhat/gocd-sdk-go"
	"github.com/nikhilsbhat/terraform-provider-gocd/pkg/utils"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func resourceAuthConfig() *schema.Resource {
	return &schema.Resource{
		CreateContext: resourceAuthConfigCreate,
		ReadContext:   resourceAuthConfigRead,
		DeleteContext: resourceAuthConfigDelete,
		UpdateContext: resourceAuthConfigUpdate,
		Schema: map[string]*schema.Schema{
			"profile_id": {
				Type:        schema.TypeString,
				Required:    true,
				Computed:    false,
				ForceNew:    true,
				Description: "The identifier of the authorization configuration.",
			},
			"plugin_id": {
				Type:        schema.TypeString,
				Required:    true,
				Computed:    false,
				ForceNew:    true,
				Description: "The plugin identifier of the authorization plugin.",
			},
			"allow_only_known_users_to_login": {
				Type:        schema.TypeBool,
				Optional:    true,
				Computed:    false,
				ForceNew:    true,
				Description: "Allow only those users to login who have explicitly been added by an administrator.",
			},
			"properties": propertiesSchema(),
			"etag": {
				Type:        schema.TypeString,
				Required:    false,
				Computed:    true,
				ForceNew:    false,
				Description: "Etag used to track the plugin settings",
			},
		},
	}
}

func resourceAuthConfigCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	defaultConfig := meta.(gocd.GoCd)

	if d.IsNewResource() {
		id := d.Id()

		if len(id) == 0 {
			newID, err := utils.GetRandomID()
			if err != nil {
				d.SetId("")

				return diag.Errorf("errored while fetching randomID %v", err)
			}
			id = newID
		}

		cfg := gocd.CommonConfig{
			ID:                  utils.String(d.Get(utils.TerraformResourceProfileID)),
			PluginID:            utils.String(d.Get(utils.TerraformPluginID)),
			Properties:          getPluginConfiguration(d.Get(utils.TerraformProperties)),
			AllowOnlyKnownUsers: utils.Bool(d.Get(utils.TerraformResourceAllowKnownUser)),
		}

		_, err := defaultConfig.CreateAuthConfig(cfg)
		if err != nil {
			return diag.Errorf("creating auth configuration %s errored with %v", cfg.ID, err)
		}

		d.SetId(id)

		return resourceAuthConfigRead(ctx, d, meta)
	}

	return nil
}

func resourceAuthConfigRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	defaultConfig := meta.(gocd.GoCd)

	profileID := utils.String(d.Get(utils.TerraformResourceProfileID))
	response, err := defaultConfig.GetAuthConfig(profileID)
	if err != nil {
		return diag.Errorf("getting auth configuration %s errored with: %v", profileID, err)
	}

	if err = d.Set(utils.TerraformResourceEtag, response.ETAG); err != nil {
		return diag.Errorf("setting etag errored with %v", err)
	}

	return nil
}

func resourceAuthConfigUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	defaultConfig := meta.(gocd.GoCd)

	if d.HasChange(utils.TerraformProperties) {
		oldCfg, newCfg := d.GetChange(utils.TerraformProperties)
		if !cmp.Equal(oldCfg, newCfg) {
			cfg := gocd.CommonConfig{
				ID:                  utils.String(d.Get(utils.TerraformResourceProfileID)),
				PluginID:            utils.String(d.Get(utils.TerraformPluginID)),
				Properties:          getPluginConfiguration(newCfg),
				AllowOnlyKnownUsers: utils.Bool(d.Get(utils.TerraformResourceAllowKnownUser)),
				ETAG:                utils.String(d.Get(utils.TerraformResourceEtag)),
			}

			_, err := defaultConfig.UpdateAuthConfig(cfg)
			if err != nil {
				return diag.Errorf("updating auth configuration %s errored with: %v", cfg.ID, err)
			}

			return resourceAuthConfigRead(ctx, d, meta)
		}
	}

	log.Printf("nothing to update so skipping")

	return nil
}

func resourceAuthConfigDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	defaultConfig := meta.(gocd.GoCd)

	id := d.Id()
	if len(d.Id()) == 0 {
		return diag.Errorf("resource with the ID '%s' not found", id)
	}

	profileID := utils.String(d.Get(utils.TerraformResourceProfileID))

	err := defaultConfig.DeleteAuthConfig(profileID)
	if err != nil {
		return diag.Errorf("deleting auth configuration %s errored with: %v", profileID, err)
	}

	d.SetId("")

	return nil
}
